USE [master]
GO

/****** Object:  Database [QlyCongTrinh]    Script Date: 12/03/2023 5:14:12 PM ******/
CREATE DATABASE [QlyCongTrinh]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QlyCongTrinh', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.LETRONGHIEP\MSSQL\DATA\QlyCongTrinh.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QlyCongTrinh_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.LETRONGHIEP\MSSQL\DATA\QlyCongTrinh_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QlyCongTrinh].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QlyCongTrinh] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET ARITHABORT OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QlyCongTrinh] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QlyCongTrinh] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QlyCongTrinh] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QlyCongTrinh] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET RECOVERY FULL 
GO

ALTER DATABASE [QlyCongTrinh] SET  MULTI_USER 
GO

ALTER DATABASE [QlyCongTrinh] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QlyCongTrinh] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QlyCongTrinh] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QlyCongTrinh] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QlyCongTrinh] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QlyCongTrinh] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QlyCongTrinh] SET QUERY_STORE = ON
GO

ALTER DATABASE [QlyCongTrinh] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [QlyCongTrinh] SET  READ_WRITE 
GO


